name: imgcmp
on:
  push:
    branches:
      - dev
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    steps:
      - uses: 9sako6/imgcmp@v2.0.4
        with:
          token: ${{ secrets.IMGCMP_ACCESS_TOKEN }}
